# highlighter: pygments
highlighter: rouge

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# markdown: kramdown
# kramdown:
#     input: GFM
#     syntax_highlighter: rouge

gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: https://monsterdogfly.github.io/
devurl: http://localhost:4000/
name: Monsterdogfly
title: Uncle and Girl
description: lijjunyao's lovely blog

my:
    displayName: monsterdogfly
    realName: Jaya Lee
    realName_cn: 李俊瑶
    jobTitle: "PM && OEI engineer"
    contact:
        qq: 542468041
        email: lijunyao@sicun.org
        github: http://www.github.com/monsterdogfly
        qzone: http://542468041.qzone.qq.com
        pinterest: None
        tel: 15527796468
        address:
            country: China
            state: Hubei Province
            city: WuHan
            distribute: HongShan
            postcode: 430074
            cell: "Huazhong University of Science and Technology"
    skills:
        frontend: [unknown]
        backend: [unknown]
        tools: [unknown]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
